### ISSUE TITLE
Breaking some non-English characters

### ISSUE THREAD

**Issue by gheritarish** [LunarWatcher/auto-pairs#65] opened 2022-06-19 08:36 UTC
**OS** Linux Garuda (arch clone), no version. Kernel Linux zen 5.18.3
**What vim? (+ version)** vim 8.2.5048
**Reproduced in other variants of Vim?** (Optional): have not

**Autopairs config** (if applicable): default

**Describe the bug**
My issue is with the "î" character (lower case only). Autopairs works fine for all other tricky characters I use (French), but this character just doesn't work. To add some strangeness: upper case works fine!

**Steps to reproduce**

uh… type "^", then "i". You should get the "î" character everywhere, but in vim with auto-pairs enabled, it fails, no letter is written. Also, if I deactivate the plugin and re-source my `vimrc` file, I can write this character.

**Comment by LunarWatcher** [comment] 2022-06-19 08:40
Most likely a dupe of #42; does `let g:AutoPairsCompatibleMaps = 0` help?

**Comment by gheritarish** [comment] 2022-06-19 08:43
Missed the #42, sorry :/
But it doesn't change anything :cry:

**Comment by LunarWatcher** [comment] 2022-06-19 08:44
What's the output of `verbose imap î`? (I think I got the right one there)

**Comment by gheritarish** [comment] 2022-06-19 08:46
Wait, it seems I lied.
I killed all my vim processes and it the `let g:AutoPairsCompatibleMaps = 0` did the trick. Thanks!

**Closed** 2022-06-19 08:52 UTC
Labels: bug, status:Triage
