### ISSUE TITLE
Can't auto-disable in TelescopePrompt

### ISSUE THREAD

**Issue by gregorias** [LunarWatcher/auto-pairs#34] opened 2021-06-11 17:58 UTC
**OS**: Manjaro
**What vim?**: Neovim 0.5

**Autopairs config**:
```
let g:AutoPairsFiletypeBlacklist = ['TelescopePrompt']
```

**Describe the bug**
Adding 'TelescopePrompt' to the blacklist doesn't work. auto-pairs continues to close parentheses in [Telescope](https://github.com/nvim-telescope/telescope.nvim).

**Steps to reproduce**
1. [Install `Telescope`](https://github.com/nvim-telescope/telescope.nvim#installation)
2. Set up auto-pairs config with `let g:AutoPairsFiletypeBlacklist = ['TelescopePrompt']`
3. Open Neovim
4. Open Telescope (with `:Telescope`, for example)
5. Type `(` in the prompt.

auto-pairs will insert `)`. I expect auto-pairs to be disabled with that setting.

**Comment by gregorias** [comment] 2021-06-11 19:24
Writing `autocmd FileType TelescopePrompt let b:autopairs_enabled` works but I would have expected `let g:AutoPairsFiletypeBlacklist = ['TelescopePrompt']` to work as well.

**Comment by LunarWatcher** [comment] 2021-06-11 19:40
Is `TelescopePrompt` the `echo &ft` of that buffer?

**Comment by gregorias** [comment] 2021-06-11 19:46
> Is `TelescopePrompt` the `echo &ft` of that buffer?

Yes. I've opened telescope, pressed ESC, and typed `:echo &ft` and saw `TelescopePrompt`. Another proof is that `autocmd FileType TelescopePrompt let b:autopairs_enabled = 0` works as expected.

**Comment by macintacos** [comment] 2021-06-11 20:37
Just nothing that I'm seeing this as well - I can use the autocmd for now though, thanks for the workaround

**Comment by LunarWatcher** [comment] 2021-06-11 21:20
I can't reproduce with
```vim
set nocompatible

filetype off

call plug#begin()
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim' 

Plug 'LunarWatcher/auto-pairs'
call plug#end()

"let g:AutoPairsFiletypeBlacklist = ['TelescopePrompt']

filetype on
filetype plugin indent on
filetype plugin on
```

Note that the blacklist is intentionally commented out - doesn't autocomplete. Doesn't run with `g:AutoPairsExperimentalAutocmd = 1` either, running `NVIM v0.5.0-dev+1127-g667e3bfb6`

**Comment by gregorias** [comment] 2021-06-12 19:41
I've used the your config on `NVIM v0.5.0-dev+1385-g93f15db5d` and it reproduced the issue for me. Here are more complete repro steps from me. Could you try them out on the newest nvim version?

Here's a more standalone minimal init.vim:

```
" init.vim
set nocompatible

filetype off

" Plugin configuration follows

" Ensure the Plug is installed
let s:target_plug_file = '~/.config/nvim/autoload/plug.vim'
if empty(glob(s:target_plug_file))
  silent !curl -fLo s:target_plug_file --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Automatically install missing plugins on startup
function! InstallMissingPlugins()
  if !empty(filter(copy(g:plugs), '!isdirectory(v:val.dir)'))
    PlugInstall
  endif
endfunction
autocmd VimEnter * :call InstallMissingPlugins()

call plug#begin()
  Plug 'nvim-lua/popup.nvim'
  Plug 'nvim-lua/plenary.nvim'
  Plug 'nvim-telescope/telescope.nvim'

  Plug 'LunarWatcher/auto-pairs'
call plug#end()

filetype on
filetype plugin indent on
filetype plugin on
```

1. Run `nvim -u init.vim foo.py`
2. If run for the first time, quit and run `nvim -u init.vim foo.py` again to make sure the plugins are loaded.
3. To verify that auto-pairs works, type `(`.
4. Run `:Telescope`.
5. Type `(` in telescope's prompt.

Step number 5 should reproduce the unwanted match. What do you see when you say that you can't reproduce?

> Note that the blacklist is intentionally commented out - doesn't autocomplete.

I don't understand why lack of autocompletion on that matters. Could you elaborate?

It's in [auto-pairs' documentation](https://github.com/LunarWatcher/auto-pairs/blob/1763e83c95394f772d942f93a409f3e16fcc91d3/doc/AutoPairs.txt#L438-L440) and doesn't behave as expected. The fact that some tooling doesn't help autocomplete a global variable seems irrelevant to the matter.

**Comment by LunarWatcher** [comment] 2021-06-12 20:00
> I don't understand why lack of autocompletion on that matters. Could you elaborate?

I meant that _pairs_ don't autocomplete in the telescope prompt, regardless of the option. I see how that sentence is ambiguous though - My bad ^^"

I'll need a little while to re-excavate my build tooling (and probably docker) to test a newer version.

**Comment by LunarWatcher** [comment] 2021-06-12 21:40
Reproduced in latest nvim nightly - mildly sus this borders a bug in neovim, however, when it's this inconsistent with other versions. Gonna have to investigate further, but first impressions: none of this makes any sense what so ever :')

My first assumption is that neovim now triggers the autocmd when a buffer is made for the popup, which also explains why it bypasses the filetype blacklist. I was right, but also wrong.

It's not just called once - it's called _four times_ without a filetype. The only component that varies between my old install and my dockerized nightly build is neovim, which means that it's either a neovim bug, or a neovim "feature". Either way, I have no idea how to fix it.

```
autocmd FileType * echom "Filetype set"
autocmd BufEnter * echom "BufEnter"
autocmd BufWinEnter * echom "BufWinEnter"
```

BufWinEnter is naturally triggered after BufEnter. Those autocmds are triggered four times with telescope. Here's the order:

```
BufEnter
BufWinEnter
# Filetype:
BufEnter
BufWinEnter
# Filetype:
BufEnter
BufWinEnter
# Filetype:
BufEnter
BufWinEnter
# Filetype:
Filetype set
```
The lines starting with `#` are auto-pairs output. Observe how the filetype is set after BufWinEnter is called.

using the autocmds above, on a rando file `:e test.py`, here's the output in Vim:

```
Filetype set
BufEnter
BufWinEnter
# auto-pairs doesn't output anything, because this is tested against my proper install that I haven't modified
```

Neovim?

```
BufEnter
BufWinEnter
# filetype: python
```

If I `set ft=cpp`, `Filetype set`. What this means is that whatever neovim did between the version I last built and now, they've _completely_ broken basic autocmd and filetype setting, making this either a wontfix or requiring some neovim-specific hack that I don't know about and won't have a chance of finding on my own.

Interestingly, though, the version I have compiled doesn't trigger `filetype` on `:e test.py` either. I'm not sure why, but telescope doesn't trigger _four separate autocmds_ in the version I have (also updated all plugins today for good measure). In fact, it only triggers the filetype autocmd. Doesn't make any sense what so ever :')

I'm going to report an upstream issue (assuming I can't find one or find something in the changelog indicating that this is intentional) either asking for this to be fixed, or asking for a workaround. If it's not a bug and there's no workarounds by design, I'll be closing this as wontfix, because I don't feel like adding code for dealing with new versions of neovim while remaining compatible with 0.4.x (which, mind you, is still the stable version).

Completely unrelated to this, I'm considering reworking some of the blacklist mechanics to not load anything auto-pairs related at all, which would exclude using `autocmd FileType`. Using that also introduces huge coordination issues in terms of loading anyway. I also can't unload all the keybinds without potentially losing information if the filetype later indicates that it's meant to be using different filetypes or not load at all. Some of this is gonna have to wait 'til tomorrow, because I don't feel like dealing with neovim making awful decisions and/or poor deployment systems when I'm this sleepy.

**Comment by gregorias** [comment] 2021-06-13 07:08
I've bisected Neovim and found the commit where this bug started happenig: https://github.com/neovim/neovim/commit/1def3d1542d6a65f057e743faea39a760b50db87. Up until https://github.com/neovim/neovim/commit/03b3ff861082ff09f2903565d928187489225306, there's no auto matching in Telescope.

I haven't looked into your comment or the neovim commit deeply yet. I intend to do so some time later.

**Comment by LunarWatcher** [comment] 2021-06-13 11:24
Initial report done: Neovim/neovim#14798

Probably gonna need to revisit later ^^'

**Comment by LunarWatcher** [comment] 2021-08-30 08:17
https://github.com/neovim/neovim/commit/1def3d1542d6a65f057e743faea39a760b50db87 was reverted in https://github.com/neovim/neovim/pull/14531, which makes no sense at all. I managed to reproduce it on my end until I updated Telescope and its dependencies, and it started working somehow. Not sure what that says about the blame, but it looks like everything is fine now?

**Comment by LunarWatcher** [comment] 2021-08-30 08:26
Just verified with a couple checkouts, https://github.com/nvim-telescope/telescope.nvim/pull/1102 somehow fixes the problem. I have no idea how. Closing this for the time being.

**Closed by LunarWatcher** 2021-08-30 08:26 UTC
Labels: bug, status:Confirmed, nvim, status:Reported upstream

**Comment by jackroi** [comment] 2024-08-04 21:25
I still have this problem on nvim v0.10.1, telescope v1.8.0, and auto-pairs v4.0.2.

**Comment by LunarWatcher** [comment] 2024-08-04 22:55
@jackroi:
I can reproduce. Either https://github.com/nvim-telescope/telescope.nvim/pull/1102 or https://github.com/neovim/neovim/issues/14798 has regressed; this isn't auto-pairs' fault. 

Using the same debugging approach as last time shows that when auto-pairs is invoked (at BufWinEnter or BufEnter[^1]), the filetype is once again wrong:

![image](https://github.com/user-attachments/assets/12c328d1-c807-461e-9b02-6ffef0609ade)

(Note that the autocmds have had `&ft` appended to the output)

That means the bug from last time, not caused by auto-pairs, has regressed. I will not be writing a workaround for this recurring nvim and/or telescope bug.

Open an issue in nvim's repo. It's either their fault, or telescope's fault, or both (again). You can also try not using nvim, which seems to break vim compatibility on a regular basis. This fork of auto-pairs is first and foremost a vim plugin. Nvim only has support as long as it doesn't sufficiently break _core and standard vimscript functionality_, which nvim happens to be notorious for doing on a regular basis. I don't mind adding minor things to get nvim to work, but breaking standard and established functionality is not something I want to work around.

Failing that, there are nvim-specific auto-pair plugins that work with nvim's non-standard behaviour. Seeing as nvim is drifting towards a full vim/nvim separation, that switch might be inevitable anyway. 

[^1]:  It's supposed to be BufWinEnter by default. There's actually a minor bug around how this is set up caused by the variables not being loaded before the autocmd is declared. It does not matter though, because the filetype is wrong in **both** autocmds, because nvim.
